### ISSUE TITLE
Create a GitHub landing page

### ISSUE THREAD

**Issue by atapas** [tapascript/.github#1]
Create a full-fledge GitHub landing page for the tapaScript GitHub.

**Comment by VETREA** [comment]
@atapas 
can you explain more clearly for this issue?

**Comment by anshumanSathua** [comment]
Hey there! 👋
This is Anshuman from the discord, this is my github link -> https://github.com/anshumanSathua, this is my github id-anshumanSathua
Please share the specs and assign it to me.

**Comment by atapas** [comment]
> Hey there! 👋 This is Anshuman from the discord, this is my github link -> https://github.com/anshumanSathua, this is my github id-anshumanSathua Please share the specs and assign it to me.

Thanks @anshumanSathua for showing interest.

I shall share the spec anytime tmorrow.

**Comment by atapas** [comment]
@anshumanSathua 

Here are the things I am thinking but please go with also what you think may work best..

- [ ] Logo
- [ ] All Socials (youtube, website, twitter, discord, email)
- [ ] A bit about tapaScript
- [ ] Who should join tapaScript?
- [ ] YouTube Badge
- [ ] Embedding this video: https://www.youtube.com/watch?v=90BgcWNRFMk
- [ ] About Sponsoring
